// Auto-generated by: npx supabase gen types typescript
// Run `task types:generate` to regenerate after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          role: 'admin' | 'sales_manager' | 'sales_rep' | 'customer_success' | 'marketing';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: 'admin' | 'sales_manager' | 'sales_rep' | 'customer_success' | 'marketing';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: 'admin' | 'sales_manager' | 'sales_rep' | 'customer_success' | 'marketing';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          metadata: Json;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          ip_address?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'audit_logs_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string | null;
          link: string | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message?: string | null;
          link?: string | null;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string | null;
          link?: string | null;
          is_read?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      app_settings: {
        Row: {
          key: string;
          value: Json;
          updated_at: string;
        };
        Insert: {
          key: string;
          value?: Json;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      pipelines: {
        Row: {
          id: string;
          name: string;
          type: 'projecten' | 'rfp' | 'consultancy';
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'projecten' | 'rfp' | 'consultancy';
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'projecten' | 'rfp' | 'consultancy';
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      pipeline_stages: {
        Row: {
          id: string;
          pipeline_id: string;
          name: string;
          sort_order: number;
          probability: number;
          color: string;
          is_closed: boolean;
          is_won: boolean;
          is_longterm: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pipeline_id: string;
          name: string;
          sort_order?: number;
          probability?: number;
          color?: string;
          is_closed?: boolean;
          is_won?: boolean;
          is_longterm?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pipeline_id?: string;
          name?: string;
          sort_order?: number;
          probability?: number;
          color?: string;
          is_closed?: boolean;
          is_won?: boolean;
          is_longterm?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'pipeline_stages_pipeline_id_fkey';
            columns: ['pipeline_id'];
            isOneToOne: false;
            referencedRelation: 'pipelines';
            referencedColumns: ['id'];
          },
        ];
      };
      indexation_indices: {
        Row: {
          id: string;
          name: string;
          value: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          value: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          value?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      accounts: {
        Row: {
          id: string;
          name: string;
          domain: string | null;
          type: 'Klant' | 'Prospect' | 'Partner';
          status: 'Actief' | 'Inactief';
          industry: string | null;
          size: string | null;
          revenue: number | null;
          phone: string | null;
          website: string | null;
          address: string | null;
          country: string | null;
          vat_number: string | null;
          owner_id: string | null;
          health: number | null;
          managing_partner: string | null;
          account_director: string | null;
          team: string | null;
          about: string | null;
          phpro_contract: 'Geen' | 'Actief' | 'Inactief' | 'In onderhandeling';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          domain?: string | null;
          type?: 'Klant' | 'Prospect' | 'Partner';
          status?: 'Actief' | 'Inactief';
          industry?: string | null;
          size?: string | null;
          revenue?: number | null;
          phone?: string | null;
          website?: string | null;
          address?: string | null;
          country?: string | null;
          vat_number?: string | null;
          owner_id?: string | null;
          health?: number | null;
          managing_partner?: string | null;
          account_director?: string | null;
          team?: string | null;
          about?: string | null;
          phpro_contract?: 'Geen' | 'Actief' | 'Inactief' | 'In onderhandeling';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          domain?: string | null;
          type?: 'Klant' | 'Prospect' | 'Partner';
          status?: 'Actief' | 'Inactief';
          industry?: string | null;
          size?: string | null;
          revenue?: number | null;
          phone?: string | null;
          website?: string | null;
          address?: string | null;
          country?: string | null;
          vat_number?: string | null;
          owner_id?: string | null;
          health?: number | null;
          managing_partner?: string | null;
          account_director?: string | null;
          team?: string | null;
          about?: string | null;
          phpro_contract?: 'Geen' | 'Actief' | 'Inactief' | 'In onderhandeling';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'accounts_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      account_manual_services: {
        Row: {
          id: string;
          account_id: string;
          service_name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          service_name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          service_name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'account_manual_services_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
        ];
      };
      account_tech_stacks: {
        Row: {
          id: string;
          account_id: string;
          technology: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          technology: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          technology?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'account_tech_stacks_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
        ];
      };
      account_samenwerkingsvormen: {
        Row: {
          id: string;
          account_id: string;
          type: 'Project' | 'Continuous Dev.' | 'Ad Hoc' | 'Support' | 'Consultancy';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          type: 'Project' | 'Continuous Dev.' | 'Ad Hoc' | 'Support' | 'Consultancy';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          type?: 'Project' | 'Continuous Dev.' | 'Ad Hoc' | 'Support' | 'Consultancy';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'account_samenwerkingsvormen_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
        ];
      };
      account_hosting: {
        Row: {
          id: string;
          account_id: string;
          provider: string;
          environment: string | null;
          url: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          provider: string;
          environment?: string | null;
          url?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          provider?: string;
          environment?: string | null;
          url?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'account_hosting_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
        ];
      };
      account_competence_centers: {
        Row: {
          id: string;
          account_id: string;
          cc_name: string;
          contact_person: string | null;
          email: string | null;
          phone: string | null;
          distribution: '4%' | '50/50' | null;
          services: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          cc_name: string;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          distribution?: '4%' | '50/50' | null;
          services?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          cc_name?: string;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          distribution?: '4%' | '50/50' | null;
          services?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'account_competence_centers_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
        ];
      };
      account_services: {
        Row: {
          id: string;
          account_id: string;
          service_name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          service_name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          service_name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'account_services_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
        ];
      };
      contacts: {
        Row: {
          id: string;
          account_id: string;
          first_name: string;
          last_name: string;
          email: string | null;
          phone: string | null;
          title: string | null;
          role: 'Decision Maker' | 'Influencer' | 'Champion' | 'Sponsor' | 'Technisch' | 'Financieel' | 'Operationeel' | 'Contact' | null;
          is_steerco: boolean;
          is_pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          first_name: string;
          last_name: string;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          role?: 'Decision Maker' | 'Influencer' | 'Champion' | 'Sponsor' | 'Technisch' | 'Financieel' | 'Operationeel' | 'Contact' | null;
          is_steerco?: boolean;
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          first_name?: string;
          last_name?: string;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          role?: 'Decision Maker' | 'Influencer' | 'Champion' | 'Sponsor' | 'Technisch' | 'Financieel' | 'Operationeel' | 'Contact' | null;
          is_steerco?: boolean;
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'contacts_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
        ];
      };
      contact_personal_info: {
        Row: {
          id: string;
          contact_id: string;
          hobbies: string[];
          marital_status: string | null;
          has_children: boolean | null;
          children_count: number | null;
          children_names: string | null;
          birthday: string | null;
          partner_name: string | null;
          partner_profession: string | null;
          notes: string | null;
          invite_dinner: boolean | null;
          invite_event: boolean | null;
          invite_gift: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          contact_id: string;
          hobbies?: string[];
          marital_status?: string | null;
          has_children?: boolean | null;
          children_count?: number | null;
          children_names?: string | null;
          birthday?: string | null;
          partner_name?: string | null;
          partner_profession?: string | null;
          notes?: string | null;
          invite_dinner?: boolean | null;
          invite_event?: boolean | null;
          invite_gift?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          contact_id?: string;
          hobbies?: string[];
          marital_status?: string | null;
          has_children?: boolean | null;
          children_count?: number | null;
          children_names?: string | null;
          birthday?: string | null;
          partner_name?: string | null;
          partner_profession?: string | null;
          notes?: string | null;
          invite_dinner?: boolean | null;
          invite_event?: boolean | null;
          invite_gift?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'contact_personal_info_contact_id_fkey';
            columns: ['contact_id'];
            isOneToOne: true;
            referencedRelation: 'contacts';
            referencedColumns: ['id'];
          },
        ];
      };
      communications: {
        Row: {
          id: string;
          account_id: string;
          contact_id: string | null;
          deal_id: string | null;
          type: 'email' | 'note' | 'meeting' | 'call';
          subject: string;
          to: string | null;
          date: string;
          duration_minutes: number | null;
          content: Json | null;
          is_done: boolean;
          owner_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          contact_id?: string | null;
          deal_id?: string | null;
          type: 'email' | 'note' | 'meeting' | 'call';
          subject: string;
          to?: string | null;
          date?: string;
          duration_minutes?: number | null;
          content?: Json | null;
          is_done?: boolean;
          owner_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          contact_id?: string | null;
          deal_id?: string | null;
          type?: 'email' | 'note' | 'meeting' | 'call';
          subject?: string;
          to?: string | null;
          date?: string;
          duration_minutes?: number | null;
          content?: Json | null;
          is_done?: boolean;
          owner_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'communications_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'communications_contact_id_fkey';
            columns: ['contact_id'];
            isOneToOne: false;
            referencedRelation: 'contacts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'communications_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      deals: {
        Row: {
          id: string;
          title: string;
          account_id: string;
          pipeline_id: string;
          stage_id: string;
          amount: number | null;
          close_date: string | null;
          probability: number | null;
          owner_id: string | null;
          description: string | null;
          contact_id: string | null;
          lead_source: string | null;
          origin: 'rechtstreeks' | 'cronos' | null;
          cronos_cc: string | null;
          cronos_contact: string | null;
          cronos_email: string | null;
          bench_consultant_id: string | null;
          consultant_role: string | null;
          forecast_category: 'Commit' | 'Best Case' | 'Pipeline' | 'Omit' | null;
          closed_at: string | null;
          closed_type: 'won' | 'lost' | 'longterm' | null;
          closed_reason: string | null;
          closed_notes: string | null;
          longterm_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          account_id: string;
          pipeline_id: string;
          stage_id: string;
          amount?: number | null;
          close_date?: string | null;
          probability?: number | null;
          owner_id?: string | null;
          description?: string | null;
          contact_id?: string | null;
          lead_source?: string | null;
          origin?: 'rechtstreeks' | 'cronos' | null;
          cronos_cc?: string | null;
          cronos_contact?: string | null;
          cronos_email?: string | null;
          bench_consultant_id?: string | null;
          consultant_role?: string | null;
          forecast_category?: 'Commit' | 'Best Case' | 'Pipeline' | 'Omit' | null;
          closed_at?: string | null;
          closed_type?: 'won' | 'lost' | 'longterm' | null;
          closed_reason?: string | null;
          closed_notes?: string | null;
          longterm_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          account_id?: string;
          pipeline_id?: string;
          stage_id?: string;
          amount?: number | null;
          close_date?: string | null;
          probability?: number | null;
          owner_id?: string | null;
          description?: string | null;
          contact_id?: string | null;
          lead_source?: string | null;
          origin?: 'rechtstreeks' | 'cronos' | null;
          cronos_cc?: string | null;
          cronos_contact?: string | null;
          cronos_email?: string | null;
          bench_consultant_id?: string | null;
          consultant_role?: string | null;
          forecast_category?: 'Commit' | 'Best Case' | 'Pipeline' | 'Omit' | null;
          closed_at?: string | null;
          closed_type?: 'won' | 'lost' | 'longterm' | null;
          closed_reason?: string | null;
          closed_notes?: string | null;
          longterm_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'deals_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'deals_pipeline_id_fkey';
            columns: ['pipeline_id'];
            isOneToOne: false;
            referencedRelation: 'pipelines';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'deals_stage_id_fkey';
            columns: ['stage_id'];
            isOneToOne: false;
            referencedRelation: 'pipeline_stages';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'deals_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'deals_contact_id_fkey';
            columns: ['contact_id'];
            isOneToOne: false;
            referencedRelation: 'contacts';
            referencedColumns: ['id'];
          },
        ];
      };
      activities: {
        Row: {
          id: string;
          type: 'Meeting' | 'Demo' | 'Call' | 'E-mail' | 'Lunch' | 'Event';
          subject: string;
          date: string;
          duration_minutes: number | null;
          account_id: string;
          deal_id: string | null;
          owner_id: string | null;
          notes: Json | null;
          is_done: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: 'Meeting' | 'Demo' | 'Call' | 'E-mail' | 'Lunch' | 'Event';
          subject: string;
          date: string;
          duration_minutes?: number | null;
          account_id: string;
          deal_id?: string | null;
          owner_id?: string | null;
          notes?: Json | null;
          is_done?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: 'Meeting' | 'Demo' | 'Call' | 'E-mail' | 'Lunch' | 'Event';
          subject?: string;
          date?: string;
          duration_minutes?: number | null;
          account_id?: string;
          deal_id?: string | null;
          owner_id?: string | null;
          notes?: Json | null;
          is_done?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'activities_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'activities_deal_id_fkey';
            columns: ['deal_id'];
            isOneToOne: false;
            referencedRelation: 'deals';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'activities_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      tasks: {
        Row: {
          id: string;
          title: string;
          due_date: string | null;
          priority: 'High' | 'Medium' | 'Low';
          status: 'Open' | 'In Progress' | 'Done';
          account_id: string | null;
          deal_id: string | null;
          assigned_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          due_date?: string | null;
          priority?: 'High' | 'Medium' | 'Low';
          status?: 'Open' | 'In Progress' | 'Done';
          account_id?: string | null;
          deal_id?: string | null;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          due_date?: string | null;
          priority?: 'High' | 'Medium' | 'Low';
          status?: 'Open' | 'In Progress' | 'Done';
          account_id?: string | null;
          deal_id?: string | null;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'tasks_account_id_fkey';
            columns: ['account_id'];
            isOneToOne: false;
            referencedRelation: 'accounts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'tasks_deal_id_fkey';
            columns: ['deal_id'];
            isOneToOne: false;
            referencedRelation: 'deals';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'tasks_assigned_to_fkey';
            columns: ['assigned_to'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_user_role: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
